FROM ft-rails:on-build

EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

# TO BUILD
# docker build -t ex02 .
# TO RUN
# docker run -it --rm -p 3000:3000 ex02
# to run in background docker run -it --rm -p 3000:3000 -d ex02